on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  train:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Create or update Azure Machine Learning job
        run: az ml job create --file ./src/job.yml --resource-group Rujhaan --workspace-name aml1
      - name: Placeholder
        run: |
          echo "Successful Job 1"

  lint-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install flake8 
          python -m pip install pytest
      - name: Run linting
        if: always ()
        continue-on-error: true
        run: |
          flake8 src/model/
      - name: Run unit tests
        run: |
          pytest src/model/
